# Generated by Django 6.0.2 on 2026-02-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="category_name",
        ),
    ]
